# Node.js 이미지를 기반으로 사용
FROM node:20.9.0

# 앱 디렉토리 생성
# 컨테이너 내에서 애플리케이션을 실행할 디렉토리를 /usr/src/app로 설정
# 이 디렉토리가 애플리케이션의 작업 디렉토리가 됨 
WORKDIR /usr/src/app

# 필요한 파일 복사 (package.json, package-lock.json)
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY lib lib
COPY node_modules node_modules
COPY public public
COPY router router
COPY app.js app.js

# 포트 설정
EXPOSE 7080

# 앱 실행
# 컨테이너가 시작될 때 실행될 명령어를 정의
CMD node app.js