# Node.js 이미지를 기반으로 사용
FROM node:20.9.0

# 앱 디렉토리 생성
# 컨테이너 내에서 애플리케이션을 실행할 디렉토리를 /usr/src/app로 설정
# 이 디렉토리가 애플리케이션의 작업 디렉토리가 됨 
WORKDIR /usr/src/app

# 이벤트 리스너 한계 늘리기
ENV NODE_OPTIONS="--max-old-space-size=8192"

# 필요한 파일 복사 (package.json, package-lock.json, .bablerc, webpack.config.js)
COPY package*.json ./
COPY .babelrc ./
COPY webpack.config.js ./


# 의존성 설치
RUN npm install


# 소스 코드 복사
COPY public public
COPY src src

# 포트 설정
EXPOSE 7070

# 앱 실행
CMD ["npm", "start"]